language: c++

sudo: required

services: docker 

install:
  - docker pull devkitpro/devkitarm

script:
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/ParentalUnlock devkitpro/devkitarm /bin/bash -ex /ParentalUnlock/.travis/docker.sh
  
